---

- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install add-apt-repostory
  apt:
    name: software-properties-common
    state: latest

- name: add oracle java repository
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: accept license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: install java
  apt:
    name:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    state: latest
